name: Post Blog on Hashnode
on: push
jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Greet user
        run: echo Hello, world!s
    
