on:
  push:
  repository_dispatch:
      types: [trigger]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to publish article on Hashnode

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Publish file on Hashnode
        id: print
        uses: iammarmirza/hello-world-javascript-action@v2.4.3
        with:
          hashnode_host: "ammarmirza.hashnode.dev"
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}
          added_files: ${{steps.changed-files.outputs.added_files}}
          modified_files: ${{steps.changed-files.outputs.modified_files}}
          deleted_files: ${{steps.changed-files.outputs.deleted_files}}
          hashnode_event: ${{toJson(github.event.client_payload)}}
        
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
