on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to print file

    steps:
      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.5.4
        with:
          file: "README.md"
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}

      - name: Get the output file name
        run: echo "The file name is ${{ steps.print.outputs.file_name }}"

      - name: Get the hashnode token
        run: echo "The Hashnode Token is ${{ steps.print.outputs.hashnode_token }}"
