on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to print file

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      
      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.5.7
        with:
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Get the hashnode token
        run: echo "The Hashnode Token is ${{ steps.print.outputs.hashnode_token }}"
