on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to print file

    steps:
      
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1

      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.6.0
        with:
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Get the hashnode token
        run: echo "The Hashnode Token is ${{ steps.print.outputs.hashnode_token }}"

      - name: Get all changed files
        env: 
          ALL_CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
        run: echo "The changed files are ${{env.ALL_CHANGED_FILES}}"
