on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.5.2
        with:
          file: "test.md"

      - name: Get the output file name
        run: echo "The time was ${{ steps.print.outputs.file_name }}"

      - name: Get the hashnode token
        run: echo "The Hashnode Token is ${{ steps.print.outputs.hashnode_token }}"
