on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to print file

    steps:
      
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          separator: ","

      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.6.3
        with:
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Get all changed files
        env: 
          ALL_CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
        run: echo "The changed files are ${{env.ALL_CHANGED_FILES}}"
      
      - name: Get all modified files
        env:
          MODIFIED_FILES: ${{steps.changed-files.outputs.modified_files}}
        run: echo "The modified files are ${{env.MODIFIED_FILES}}"
      
      - name: Get all deleted files
        env: 
          DELETED_FILES: ${{steps.changed-files.outputs.deleted_files}}
        run: echo "The deleted files are ${{env.DELETED_FILES}}"