on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v1.5.3
        with:
          file: "test.md"
          hashnode_token: ${{secrets.GITHUB_TOKEN}}

      - name: Get the output file name
        run: echo "The file name is ${{ steps.print.outputs.file_name }}"

      - name: Get the hashnode token
        run: echo "The Hashnode Token is ${{ steps.print.outputs.hashnode_token }}"
