on: [push]

jobs:
  print_file_job:
    runs-on: ubuntu-latest
    name: A job to print file

    steps:
      
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1

      - name: Print file action step
        id: print
        uses: iammarmirza/hello-world-javascript-action@v2.1.3
        with:
          hashnode_host: 'ammarmirza.hashnode.dev'
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}
          github_token: ${{secrets.GITHUB_TOKEN}}
          added_files: ${{steps.changed-files.outputs.added_files}}
          modified_files: ${{steps.changed-files.outputs.modified_files}}
          deleted_files: ${{steps.changed-files.outputs.deleted_files}}
